
# build file for Corrade docker container

FROM debian:stable-slim
LABEL maintainer="ch@sysconfig.org.uk"
EXPOSE 54377



WORKDIR /corrade

RUN apt-get install -y apt
RUN apt-get update -y
RUN apt-get upgrade -y

# pre-requisites (dotnet) need to come from Microsoft on Debian

RUN apt-get install -y wget gpg apt-transport-https busybox unzip procps perl-modules libterm-readline-gnu-perl || true
RUN dpkg-reconfigure -f noninteractive debconf
RUN wget -qO - https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
RUN mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
RUN wget -q https://packages.microsoft.com/config/debian/10/prod.list
RUN mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
RUN apt-get update -y
RUN apt-get install -y dotnet-runtime-5.0


RUN wget --no-check-certificate https://corrade.grimore.org/download/corrade/linux-x64/LATEST.zip -qO - | busybox unzip -
ADD Nucleus.xml ./
ADD Configuration.xml.template ./
ADD start-corrade.sh ./
RUN chmod 750 start-corrade.sh 
RUN chmod 750 Corrade 
RUN rm -rf /var/cache/apt/*


ENTRYPOINT ["/corrade/start-corrade.sh"]
CMD ["/corrade/start-corrade.sh"]
