
# build file for Corrade docker container

FROM debian:stable-slim
LABEL maintainer="ch@sysconfig.org.uk"
EXPOSE 54377



WORKDIR /corrade

RUN apt-get update -y
RUN apt-get upgrade -y

# pre-requisites (dotnet) need to come from Microsoft on Debian

RUN apt-get install -y wget gpg apt-transport-https busybox unzip
RUN wget https://download.visualstudio.microsoft.com/download/pr/c1f15b51-5e8c-4e6c-a803-241790159af3/b5cbcc59f67089d760e0ed4a714c47ed/dotnet-sdk-5.0.202-linux-arm64.tar.gz
RUN mkdir -p dotnet && tar zxf dotnet-sdk-5.0.202-linux-arm64.tar.gz -C dotnet



RUN wget --no-check-certificate https://corrade.grimore.org/download/corrade/linux-x64/LATEST.zip -qO - | busybox unzip -
ADD Nucleus.xml ./
ADD Configuration.xml.template ./
ADD start-corrade-aarch64.sh ./
RUN chmod 750 start-corrade-aarch64.sh 
RUN chmod 750 Corrade 
RUN rm -rf /var/cache/apt/*


ENTRYPOINT ["/corrade/start-corrade-aarch64.sh"]
CMD ["/corrade/start-corrade-aarch64.sh"]