
# build file for Corrade docker container

FROM arch-min
LABEL maintainer="ch@sysconfig.org.uk"
EXPOSE 54377


ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/corrade/dotnet
ENV DOTNET_ROOT=/corrade/dotnet

WORKDIR /corrade

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm dotnet-runtime wget unzip awk sed

RUN wget --no-check-certificate https://corrade.grimore.org/download/corrade/linux-x64/LATEST.zip
ADD Nucleus.xml ./
ADD Configuration.xml.template ./
ADD start-corrade.sh ./
RUN unzip LATEST.zip



ENTRYPOINT ["/corrade/start-corrade.sh"]
#CMD ["/corrade/start-corrade.sh"]
#ENTRYPOINT ["/bin/sh"]
